apiVersion: v1
kind: Service
metadata:
  name: rubyapp-loadbalancer
spec:
  selector:
    app: rubyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

# This section defines a LoadBalancer service for a Ruby application.
# The service listens on port 80 and directs traffic to port 3000 where the Ruby application is running.
# End of YAML Configuration
