apiVersion: v1
kind: Service
metadata:
  name: rubyapp-loadbalancer
spec:
  selector:
    app: rubyapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # The port your Ruby application is listening on
  type: LoadBalancer
